# File: .github/workflows/deploy.yml

name: Deploy Static Site to Pages

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the runs of this workflow.
# If a UI-driven deployment is queued, it will be canceled and replaced by a new one.
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup Node.js 24 (no npm project)
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false
          
      - name: Get files
        run: node ./.github/workflows/random_file_gen.ts

      - name: archive files
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "./dist" \
            -cf "artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            --exclude=".[^/]*" \
            . > /dev/null 2>&1
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
  
  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      # Step to delete the artifact after successful deployment
      - name: Delete build artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          # The name of the artifact to delete
          name: github-pages
